-- Clean up duplicate "Despesa fixa" transaction generated by edge function
DELETE FROM transactions WHERE id = 'dfb5c672-5dfe-406d-90b6-032f68b6988d';

-- Clean up the generic "Despesa fixa" recurring payment (user already has "Aluguel" as their actual entry)
DELETE FROM recurring_payments WHERE id = '20d4d3f0-a015-46ef-9004-1066d1aaeaa7';