// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zyfevttmauoejmsranwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5ZmV2dHRtYXVvZWptc3JhbndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NjE5OTcsImV4cCI6MjA4OTUzNzk5N30.grNww08CkAsELz53cF6qiM0KiwQezvDa2UshcCeKbzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
