// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iscwvmwgqtajnwqqqeky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzY3d2bXdncXRham53cXFxZWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MTA4MzgsImV4cCI6MjA4NTk4NjgzOH0.nI05hZiHJ1WJkbc-x7gjjAmba4zeAMZBHmAKx6ov4cU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});